FROM openjdk:17-jdk-alpine
LABEL maintainer="backendchallenge2024@gmail.com"
ADD target/TechTrendEmporium-0.0.1-SNAPSHOT.jar techtrendemporium-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","techtrendemporium-0.0.1-SNAPSHOT.jar"]