name: CI

on:
  push:
    branches: 
      - 'feature-*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build
      uses: docker/build-push-action@v5
      with:
        context: ./TechTrendEmporium/TechTrendEmporium/
        load: true
        tags: backendchallenge2024/tech-trend-emporium:${{ github.sha }}

  test:

    runs-on: ubuntu-latest

    needs: build

    steps:

    - name: Test
      # run: docker run tech-trend-emporium
      run: |
        echo "Testing the app" 
  
  release:

    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: ./TechTrendEmporium/TechTrendEmporium/
          push: true
          tags: backendchallenge2024/tech-trend-emporium:${{ github.sha }}